server:
  port: 8001
spring:
  application:
    name: microservice.product.service
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msproduct?createDatabaseIfNotExist=true&useUnicode=true&autoReconnect=true
    username: msecom
    password: msecom
    initialize: false

management:
  endpoints:
    web:
      exposure:
        include: '*'


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql:
      BasicBinder: TRACE
      BasicExtractor: TRACE
    com.bdtv: DEBUG

mockEnabled: false