server:
  port: 8002
spring:
  jpa:
    show-sql: true
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-product:3306/msproduct?useSSL=false
    username: msecom
    password: msecom

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-eureka:8761/eureka/

mockEnabled: true